### ISSUE TITLE
Stuck processing

### ISSUE THREAD

**Issue by initial0ddx** [dstacey/BPCS#1]
Hello, thank you for sharing your source code ...
I had tried to running your program but it stuck after input vessel image and input data to hide
is there something wrong about the program?
thanks in advance
![stuck](https://cloud.githubusercontent.com/assets/7892921/7580746/de9dd85e-f8a4-11e4-9caf-e8c1cb1477b0.png)

**Comment by dstacey** [comment]
Thank you for your interest in my project. I noticed that the screenshot you posted is in Java. My project will be in Python, once I start writing the code, which I plan to do this summer. Feel free to clone this repository so you can get the latest code when it's posted.

Thanks,
David
